### ISSUE TITLE
Tenant title so ugly

### ISSUE THREAD

**Issue by desmfr** [MAIF/daikoku#143]
**Describe the bug**
The wrotten title appears even if the logo was defines and uploaded. It is a mess in the topbar, you hurt my feelings and my eyes cry.

**To Reproduce**
1. Connect to your ******* UI
2. Look at the ugly top bar

**Expected behavior**
having a nice topbar

**Comment by baudelotphilippe** [comment]
You know, it's fully customisable, and sometimes it will be very weird, but it is art :)

For the title, sometimes the logo is not enough and the title stay here to complete the information.
Maybe we can move it in the img ALT
