### ISSUE TITLE
Tenant redirection is broken

### ISSUE THREAD

**Issue by guillaumesoldera** [MAIF/daikoku#234]
After tenant creation, on Tenants home screen, when I try to redirect to my tenant with the link icon, I'm redirected to my URL but `8080` port is added.

![image](https://user-images.githubusercontent.com/422144/113690684-f6519000-96cb-11eb-9c1f-e826d7800d2a.png)

![image](https://user-images.githubusercontent.com/422144/113690726-fea9cb00-96cb-11eb-82dc-6930a6726eb5.png)

**Comment by quentinovega** [comment]
@guillaumesoldera, You can now configure an exposed port for your Tenant.
