### ISSUE TITLE
Star button too large when API title is too long

### ISSUE THREAD

**Issue by sadmin91** [MAIF/daikoku#243]
**Describe the bug**
When an API title is too long (on 2 lines), star button of this API is too large.

**To Reproduce**
Go to API list (page /apis) and go to an API with long title.

**Expected behavior**
Star button will be show with an height of one line

**Screenshots**
![image](https://user-images.githubusercontent.com/6031110/116204002-971bf400-a73c-11eb-9e87-20bf9ac19837.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 88

**Comment by quentinovega** [comment]
FIX in https://github.com/MAIF/daikoku/issues/243
