### ISSUE TITLE
Patch API doesn’t sync with Otoroshi

### ISSUE THREAD

**Issue by sadmin91** [MAIF/daikoku#422]
**Describe the bug**
I use the patch API endpoint of Daikoku Admin APIs to update some Otoroshi parameters defined on an API exposed with Daikoku.
After a successfull call of this Admin API, the synchronisation process between Daikoku & Otoroshi is not trigger.

**To Reproduce**
1. Update an Otoroshi metadata via the patch API endpoint of Daikoku Admin APIs
2. On Otoroshi API Key, metadata is not updated

**Expected behavior**
When the patch API endpoint of Daikoku Admin APIs is successfull, trigger the synchronisation process between Daikoku & Otoroshi.

**Additional context**
Daikoku version: 1.5.0

**Comment by quentinovega** [comment]
it's totally normal, the admin APIs does just its job, if you want to trigger the synchro between otoroshi and daikoku, you can call the sync API (<url>/api/jobs/otoroshi/_sync?key=<daikoku.otoroshi.sync.key>) or, you wait the sync job cron run.
