### ISSUE TITLE
When adding an empty tag or an empty supported version, all the other ones are deleted even those who are already saved 

### ISSUE THREAD

**Issue by baudelotphilippe** [MAIF/daikoku#557]
it's not save

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/27761959/232766402-cb7bd1b8-269d-41f4-af6f-527a7a8f1d7d.png">

**Comment by Btxgear** [comment]
Create some tags/supported versions and save them. them create an empty one and save it.
