### ISSUE TITLE
Test if the email is good in alerting zone

### ISSUE THREAD

**Issue by baudelotphilippe** [MAIF/daikoku#565]
In security Alerting (paramaters) we can put anything. May be restrict to an email.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/27761959/233390344-b20bc09c-be86-4a4e-91f0-019e5513374e.png">

**Comment by Btxgear** [comment]
Add a better display of the constraints
<img width="1101" alt="Capture d’écran 2023-05-04 à 10 35 36" src="https://user-images.githubusercontent.com/84455293/236153149-d4b2582b-73d4-4a51-9c32-c08493fed108.png">
