### ISSUE TITLE
Port error 8080 => 5173

### ISSUE THREAD

**Issue by baudelotphilippe** [MAIF/daikoku#739]
This action doesn't work anymore

INFO  daikoku-console-mailer - Sent email: {
  "from" : "Daikoku <daikoku@foo.bar>",
  "to" : [ "benjamin@xxx.fr" ],
  "subject" : [ "Validation de souscription" ],
  "html" : "Bonjour,    <br/>    philippe pour léquipe Fifou's Team voudrait souscrire a lAPI [apiName],    <br>    <div>        </div><a href=\"http://localhost:8080/api/subscription/_validate?token=ldvbSqRFqPen18A_DUVrMycEeNOHxRpyVBEk6qibz4TRgrdXxU36-Rpt0C07lx1UN9AHojvJiTpm25smvSn_2z22zfRY63O9drkO2H5rVGs=\">Accept</a> or <a

It's ok if I change the port.
But after, there is another error http://localhost:8080/?message=home.message.subscription.validation.successfull

**Comment by quentinovega** [comment]
You're running daikoku locally, just add -Ddaikoku.exposedOn=5173
